# syntax=docker/dockerfile:1

FROM postgres:latest

WORKDIR /db

ENV POSTGRES_USER=docker
ENV POSTGRES_PASSWORD=docker
ENV POSTGRES_DB=test_db

COPY init-user-db.sql /docker-entrypoint-initdb.d/

EXPOSE 5432